/**
 * CF-22 — the IMPLEMENTED registry: which vendored community ops have real
 * framework handlers (vs. 501 stubs). Drives `x-implemented` in the emitted spec
 * and the burn-down count in the drift gate.
 *
 * P1: `variables` (6). P2 Wave 1: Meta (3), settings (12), Themes (3), project (3),
 * security-events (2). P2 Waves 2–5 grow this set until it equals productOps().
 */
import { opKey } from './spec.js';

/** Op keys implemented by real handlers. */
export const IMPLEMENTED: Set<string> = new Set([
    // P1 — variables (6)
    opKey('GET', '/api/variables/'),
    opKey('POST', '/api/variables/'),
    opKey('GET', '/api/variables/registry/'),
    opKey('GET', '/api/variables/{variable_id}'),
    opKey('PUT', '/api/variables/{variable_id}/'),
    opKey('DELETE', '/api/variables/{variable_id}/'),

    // P2 Wave 1 — Meta (2 implemented; bare GET / owned by the eSSR engine, not compat)
    // The vendored spec has GET / as a Meta op, but the framework's engine owns the
    // bare / path (published pages). The compat surface serves /health + /api/queue/health.
    opKey('GET', '/health'),
    opKey('GET', '/api/queue/health'),

    // P2 Wave 1 — settings (12)
    opKey('GET', '/api/settings/general'),
    opKey('PUT', '/api/settings/general'),
    opKey('GET', '/api/settings/privacy/'),
    opKey('PUT', '/api/settings/privacy/'),
    opKey('GET', '/api/settings/security/'),
    opKey('PUT', '/api/settings/security/'),
    opKey('GET', '/api/settings/redis/'),
    opKey('PUT', '/api/settings/redis/'),
    opKey('POST', '/api/settings/redis/test/'),
    opKey('POST', '/api/settings/telemetry'),
    opKey('POST', '/api/settings/validate-license'),
    opKey('POST', '/api/settings/invites'),

    // P2 Wave 1 — Themes (3)
    opKey('GET', '/api/themes/'),
    opKey('POST', '/api/themes/'),
    opKey('DELETE', '/api/themes/{theme_id}'),

    // P2 Wave 1 — project (3)
    opKey('GET', '/api/project/'),
    opKey('PUT', '/api/project/'),
    opKey('POST', '/api/project/assets/upload/'),

    // P2 Wave 1 — security-events (2)
    opKey('GET', '/api/security-events/'),
    opKey('GET', '/api/security-events/summary'),

    // P2 Wave 1b — pages (17)
    opKey('GET', '/api/pages/'),
    opKey('POST', '/api/pages/'),
    opKey('GET', '/api/pages/homepage/'),
    opKey('GET', '/api/pages/public/{slug}/'),
    opKey('GET', '/api/pages/{page_id}/'),
    opKey('PUT', '/api/pages/{page_id}/'),
    opKey('PUT', '/api/pages/{page_id}/layout/'),
    opKey('DELETE', '/api/pages/{page_id}/'),
    opKey('DELETE', '/api/pages/{page_id}/permanent/'),
    opKey('POST', '/api/pages/{page_id}/restore/'),
    opKey('POST', '/api/pages/{page_id}/publish-batch/'),
    opKey('POST', '/api/pages/{page_id}/publish/{engine_id}/'),
    opKey('POST', '/api/pages/{page_id}/unpublish/{engine_id}/'),
    opKey('GET', '/api/pages/{page_id}/versions/'),
    opKey('POST', '/api/pages/{page_id}/versions/'),
    opKey('GET', '/api/pages/{page_id}/versions/{version_id}/'),
    opKey('POST', '/api/pages/{page_id}/rollback/'),

    // P2 Wave 1b — database (10)
    opKey('GET', '/api/database/connections/'),
    opKey('POST', '/api/database/test-supabase/'),
    opKey('POST', '/api/database/connect-supabase/'),
    opKey('DELETE', '/api/database/disconnect-supabase/'),
    opKey('GET', '/api/database/tables/'),
    opKey('GET', '/api/database/supabase-tables/'),
    opKey('GET', '/api/database/table-data/{table_name}/'),
    opKey('GET', '/api/database/table-schema/{table_name}/'),
    opKey('POST', '/api/database/advanced-query/'),
    opKey('POST', '/api/database/distinct-values/'),

    // P2 Wave 1b — rls (14)
    opKey('GET', '/api/database/rls/policies/'),
    opKey('GET', '/api/database/rls/tables/'),
    opKey('GET', '/api/database/rls/policies/{table_name}'),
    opKey('POST', '/api/database/rls/policies/'),
    opKey('PUT', '/api/database/rls/policies/{table_name}/{policy_name}'),
    opKey('DELETE', '/api/database/rls/policies/{table_name}/{policy_name}'),
    opKey('POST', '/api/database/rls/tables/{table_name}/toggle/'),
    opKey('POST', '/api/database/rls/batch/'),
    opKey('POST', '/api/database/rls/bulk-delete/'),
    opKey('GET', '/api/database/rls/metadata/'),
    opKey('GET', '/api/database/rls/metadata/{table_name}/{policy_name}'),
    opKey('POST', '/api/database/rls/metadata/'),
    opKey('DELETE', '/api/database/rls/metadata/{table_name}/{policy_name}'),
    opKey('POST', '/api/database/rls/metadata/verify/'),

    // P2 Waves 2+3
    opKey('DELETE', '/api/actions/drafts/{draft_id}'),
    opKey('DELETE', '/api/auth-forms/{form_id}/'),
    opKey('DELETE', '/api/auth/security/blocklist/{ban_id}'),
    opKey('DELETE', '/api/edge-databases/{db_id}'),
    opKey('DELETE', '/api/storage/buckets/{bucket_id}'),
    opKey('DELETE', '/api/storage/delete'),
    opKey('DELETE', '/api/storage/providers/{provider_id}'),
    opKey('GET', '/api/actions/drafts'),
    opKey('GET', '/api/actions/drafts/{draft_id}'),
    opKey('GET', '/api/actions/drafts/{draft_id}/versions/'),
    opKey('GET', '/api/actions/drafts/{draft_id}/versions/{version_id}/'),
    opKey('GET', '/api/actions/execution-stats'),
    opKey('GET', '/api/actions/execution/{execution_id}'),
    opKey('GET', '/api/actions/executions'),
    opKey('GET', '/api/actions/executions/detail/{execution_id}'),
    opKey('GET', '/api/actions/executions/export'),
    opKey('GET', '/api/actions/executions/{draft_id}'),
    opKey('GET', '/api/actions/executions/{draft_id}/production/{engine_id}'),
    opKey('GET', '/api/auth-forms/'),
    opKey('GET', '/api/auth-forms/primary/'),
    opKey('GET', '/api/auth-forms/{form_id}/'),
    opKey('GET', '/api/auth/check-slug/{slug}'),
    opKey('GET', '/api/auth/invite/{token}'),
    opKey('GET', '/api/auth/me'),
    opKey('GET', '/api/auth/security/audit-logs'),
    opKey('GET', '/api/auth/security/blocklist'),
    opKey('GET', '/api/auth/security/bot-protection'),
    opKey('GET', '/api/auth/security/bot-protection/metrics'),
    opKey('GET', '/api/auth/security/waf'),
    opKey('GET', '/api/edge-databases/'),
    opKey('GET', '/api/storage/buckets'),
    opKey('GET', '/api/storage/buckets/{bucket_id}'),
    opKey('GET', '/api/storage/compute-size'),
    opKey('GET', '/api/storage/list'),
    opKey('GET', '/api/storage/move-status/{job_id}'),
    opKey('GET', '/api/storage/netlify-sites'),
    opKey('GET', '/api/storage/providers/'),
    opKey('GET', '/api/storage/public-url'),
    opKey('GET', '/api/storage/signed-url'),
    opKey('GET', '/api/storage/vercel-projects'),
    opKey('PATCH', '/api/actions/drafts/{draft_id}'),
    opKey('PATCH', '/api/actions/drafts/{draft_id}/active'),
    opKey('POST', '/api/actions/drafts'),
    opKey('POST', '/api/actions/drafts/bulk-delete'),
    opKey('POST', '/api/actions/drafts/{draft_id}/publish'),
    opKey('POST', '/api/actions/drafts/{draft_id}/publish-batch/'),
    opKey('POST', '/api/actions/drafts/{draft_id}/publish/{engine_id}/'),
    opKey('POST', '/api/actions/drafts/{draft_id}/publish/{engine_id}/toggle'),
    opKey('POST', '/api/actions/drafts/{draft_id}/rollback/'),
    opKey('POST', '/api/actions/drafts/{draft_id}/test'),
    opKey('POST', '/api/actions/drafts/{draft_id}/test-node/{node_id}'),
    opKey('POST', '/api/actions/drafts/{draft_id}/versions/'),
    opKey('POST', '/api/auth-forms/'),
    opKey('POST', '/api/auth/accept-invite'),
    opKey('POST', '/api/auth/forgot-password'),
    opKey('POST', '/api/auth/login'),
    opKey('POST', '/api/auth/logout'),
    opKey('POST', '/api/auth/reset-password'),
    opKey('POST', '/api/auth/security/blocklist'),
    opKey('POST', '/api/auth/security/bot-protection'),
    opKey('POST', '/api/auth/security/waf'),
    opKey('POST', '/api/auth/signup'),
    opKey('POST', '/api/edge-databases/'),
    opKey('POST', '/api/edge-databases/batch/delete'),
    opKey('POST', '/api/edge-databases/create-schema'),
    opKey('POST', '/api/edge-databases/discover-schemas'),
    opKey('POST', '/api/edge-databases/reset-role-password'),
    opKey('POST', '/api/edge-databases/test-connection'),
    opKey('POST', '/api/edge-databases/{db_id}/test'),
    opKey('POST', '/api/storage/buckets'),
    opKey('POST', '/api/storage/buckets/{bucket_id}/empty'),
    opKey('POST', '/api/storage/create-folder'),
    opKey('POST', '/api/storage/move'),
    opKey('POST', '/api/storage/move-cross'),
    opKey('POST', '/api/storage/netlify-sites'),
    opKey('POST', '/api/storage/providers/'),
    opKey('POST', '/api/storage/upload'),
    opKey('POST', '/api/storage/vercel-projects'),
    opKey('POST', '/api/workflows/send-email'),
    opKey('PUT', '/api/auth-forms/{form_id}/'),
    opKey('PUT', '/api/auth-forms/{form_id}/set-primary/'),
    opKey('PUT', '/api/edge-databases/{db_id}'),
    opKey('PUT', '/api/storage/buckets/{bucket_id}'),

    // P2 Waves 4+5
    opKey('DELETE', '/api/agent-profiles/{profile_id}/skills/{install_id}'),
    opKey('DELETE', '/api/agent-skills/{skill_id}'),
    opKey('DELETE', '/api/agent/settings'),
    opKey('DELETE', '/api/edge-api-keys/{key_id}'),
    opKey('DELETE', '/api/edge-caches/{cache_id}'),
    opKey('DELETE', '/api/edge-engines/{engine_id}'),
    opKey('DELETE', '/api/edge-engines/{engine_id}/agent-profiles/{profile_id}'),
    opKey('DELETE', '/api/edge-engines/{engine_id}/inspect/domains/{domain_id}'),
    opKey('DELETE', '/api/edge-gpu/{model_id}'),
    opKey('DELETE', '/api/edge-providers/{account_id}/turso-databases/{db_id}'),
    opKey('DELETE', '/api/edge-providers/{provider_id}'),
    opKey('DELETE', '/api/edge-queues/{queue_id}'),
    opKey('DELETE', '/api/edge-vectors/{vector_id}'),
    opKey('DELETE', '/api/mcp-servers/{server_id}'),
    opKey('GET', '/api/agent-catalogue'),
    opKey('GET', '/api/agent-profiles/{profile_id}/skills'),
    opKey('GET', '/api/agent-skills'),
    opKey('GET', '/api/agent/credits'),
    opKey('GET', '/api/agent/mcp/{profile_slug}'),
    opKey('GET', '/api/agent/settings'),
    opKey('GET', '/api/edge-api-keys'),
    opKey('GET', '/api/edge-api-keys/{key_id}/reveal'),
    opKey('GET', '/api/edge-caches/'),
    opKey('GET', '/api/edge-engines/'),
    opKey('GET', '/api/edge-engines/active/by-scope/{scope}'),
    opKey('GET', '/api/edge-engines/bundle-hashes/'),
    opKey('GET', '/api/edge-engines/{engine_id}'),
    opKey('GET', '/api/edge-engines/{engine_id}/agent-profiles'),
    opKey('GET', '/api/edge-engines/{engine_id}/audit/tenant-secrets'),
    opKey('GET', '/api/edge-engines/{engine_id}/health-check'),
    opKey('GET', '/api/edge-engines/{engine_id}/inspect/domains'),
    opKey('GET', '/api/edge-engines/{engine_id}/inspect/secrets'),
    opKey('GET', '/api/edge-engines/{engine_id}/inspect/settings'),
    opKey('GET', '/api/edge-engines/{engine_id}/inspect/source'),
    opKey('GET', '/api/edge-engines/{engine_id}/logs'),
    opKey('GET', '/api/edge-engines/{engine_id}/logs/retention'),
    opKey('GET', '/api/edge-engines/{engine_id}/rotation-history'),
    opKey('GET', '/api/edge-engines/{engine_id}/rotation-status'),
    opKey('GET', '/api/edge-engines/{engine_id}/source'),
    opKey('GET', '/api/edge-gpu/'),
    opKey('GET', '/api/edge-gpu/catalog'),
    opKey('GET', '/api/edge-gpu/schemas'),
    opKey('GET', '/api/edge-providers/'),
    opKey('GET', '/api/edge-providers/accounts/{account_id}/tables'),
    opKey('GET', '/api/edge-providers/workspace-agent-token'),
    opKey('GET', '/api/edge-providers/{provider_id}'),
    opKey('GET', '/api/edge-providers/{provider_id}/credentials'),
    opKey('GET', '/api/edge-queues/'),
    opKey('GET', '/api/edge-vectors/'),
    opKey('GET', '/api/mcp-servers'),
    opKey('GET', '/api/mcp-servers/{server_id}'),
    opKey('GET', '/api/mcp-servers/{server_id}/tools'),
    opKey('PATCH', '/api/edge-engines/{engine_id}/logs/config'),
    opKey('POST', '/api/agent-profiles/{profile_id}/skills'),
    opKey('POST', '/api/agent-skills'),
    opKey('POST', '/api/agent/chat'),
    opKey('POST', '/api/agent/chat/{profile_slug}'),
    opKey('POST', '/api/agent/mcp/{profile_slug}/prompts/get'),
    opKey('POST', '/api/agent/mcp/{profile_slug}/prompts/list'),
    opKey('POST', '/api/agent/mcp/{profile_slug}/resources/list'),
    opKey('POST', '/api/agent/mcp/{profile_slug}/tools/call'),
    opKey('POST', '/api/agent/mcp/{profile_slug}/tools/list'),
    opKey('POST', '/api/cloudflare/connect'),
    opKey('POST', '/api/cloudflare/deploy'),
    opKey('POST', '/api/cloudflare/inspect/content'),
    opKey('POST', '/api/cloudflare/inspect/secrets'),
    opKey('POST', '/api/cloudflare/inspect/settings'),
    opKey('POST', '/api/cloudflare/status'),
    opKey('POST', '/api/cloudflare/teardown'),
    opKey('POST', '/api/deno/connect'),
    opKey('POST', '/api/edge-api-keys'),
    opKey('POST', '/api/edge-caches/'),
    opKey('POST', '/api/edge-caches/batch/delete'),
    opKey('POST', '/api/edge-caches/test-connection'),
    opKey('POST', '/api/edge-caches/{cache_id}/test'),
    opKey('POST', '/api/edge-engines/'),
    opKey('POST', '/api/edge-engines/batch/delete'),
    opKey('POST', '/api/edge-engines/batch/redeploy'),
    opKey('POST', '/api/edge-engines/batch/rotate-secrets-key'),
    opKey('POST', '/api/edge-engines/batch/sync-check'),
    opKey('POST', '/api/edge-engines/batch/toggle'),
    opKey('POST', '/api/edge-engines/deploy'),
    opKey('POST', '/api/edge-engines/import'),
    opKey('POST', '/api/edge-engines/{engine_id}/agent-profiles'),
    opKey('POST', '/api/edge-engines/{engine_id}/cancel-move'),
    opKey('POST', '/api/edge-engines/{engine_id}/export'),
    opKey('POST', '/api/edge-engines/{engine_id}/finalize-move'),
    opKey('POST', '/api/edge-engines/{engine_id}/inspect/domains'),
    opKey('POST', '/api/edge-engines/{engine_id}/inspect/domains/{domain_id}/verify'),
    opKey('POST', '/api/edge-engines/{engine_id}/logs/sync'),
    opKey('POST', '/api/edge-engines/{engine_id}/move-to-project'),
    opKey('POST', '/api/edge-engines/{engine_id}/reconfigure'),
    opKey('POST', '/api/edge-engines/{engine_id}/redeploy'),
    opKey('POST', '/api/edge-engines/{engine_id}/rollback-rotation'),
    opKey('POST', '/api/edge-engines/{engine_id}/rotate-secrets-key'),
    opKey('POST', '/api/edge-engines/{engine_id}/sync-manifest'),
    opKey('POST', '/api/edge-engines/{engine_id}/test'),
    opKey('POST', '/api/edge-gpu/'),
    opKey('POST', '/api/edge-gpu/{model_id}/test'),
    opKey('POST', '/api/edge-providers/'),
    opKey('POST', '/api/edge-providers/create-resource-by-account/{account_id}'),
    opKey('POST', '/api/edge-providers/discover'),
    opKey('POST', '/api/edge-providers/discover-by-account/{account_id}'),
    opKey('POST', '/api/edge-providers/retest/{provider_id}'),
    opKey('POST', '/api/edge-providers/test-connection'),
    opKey('POST', '/api/edge-providers/workspace-agent-token'),
    opKey('POST', '/api/edge-providers/{account_id}/list-engines'),
    opKey('POST', '/api/edge-providers/{account_id}/turso-databases'),
    opKey('POST', '/api/edge-providers/{account_id}/turso-databases/{db_id}/test'),
    opKey('POST', '/api/edge-queues/'),
    opKey('POST', '/api/edge-queues/batch/delete'),
    opKey('POST', '/api/edge-queues/test-connection'),
    opKey('POST', '/api/edge-queues/{queue_id}/test/'),
    opKey('POST', '/api/edge-vectors/'),
    opKey('POST', '/api/edge-vectors/batch/delete'),
    opKey('POST', '/api/edge-vectors/test-connection'),
    opKey('POST', '/api/edge-vectors/{vector_id}/test'),
    opKey('POST', '/api/mcp-servers'),
    opKey('POST', '/api/mcp-servers/{server_id}/test'),
    opKey('PUT', '/api/agent-skills/{skill_id}'),
    opKey('PUT', '/api/agent/settings'),
    opKey('PUT', '/api/edge-api-keys/{key_id}'),
    opKey('PUT', '/api/edge-caches/{cache_id}'),
    opKey('PUT', '/api/edge-engines/{engine_id}'),
    opKey('PUT', '/api/edge-engines/{engine_id}/agent-profiles/{profile_id}'),
    opKey('PUT', '/api/edge-engines/{engine_id}/source'),
    opKey('PUT', '/api/edge-gpu/{model_id}'),
    opKey('PUT', '/api/edge-providers/{provider_id}'),
    opKey('PUT', '/api/edge-queues/{queue_id}'),
    opKey('PUT', '/api/edge-vectors/{vector_id}'),
    opKey('PUT', '/api/mcp-servers/{server_id}'),
]);
