import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {sqliteRunner} from '@frontbase/edge-infra';
import {TENANT} from './fixture-data';
const bootstrap=JSON.parse(readFileSync(join(tmpdir(),'pilot-quality-run','bootstrap.json'),'utf8'));
const state=JSON.parse(readFileSync(bootstrap.statePath,'utf8'));
test('first publication through existing admin requires checked inactive state and explicit confirmation',async({page})=>{
 // Remove only this temporary fixture's preseeded pointer; captures/reviews remain invented and intact.
 await sqliteRunner(bootstrap.dbUrl).exec('DELETE FROM settings WHERE tenant_slug = ? AND key = ?',[TENANT,'site_publication:active:v1']);
 await page.goto('/frontbase-admin/login');await page.locator('input[type="email"]').fill(state.admin.email);await page.locator('input[type="password"]').fill(state.admin.password);
 await page.locator('button[type="submit"]').click();await page.waitForURL(/dashboard|pages/);
 await page.goto(`/frontbase-admin/builder/${state.templatePageIds.directory}`);await page.getByTitle('Page Settings',{exact:true}).click();await page.getByRole('tab',{name:'Directory',exact:true}).click();
 const preparation=page.getByRole('region',{name:'Site preparation',exact:true});await preparation.getByLabel('Prepared version ID',{exact:true}).fill(state.hashActive);await preparation.getByRole('button',{name:'Reopen private version',exact:true}).click();
 const publishing=page.getByRole('region',{name:'Publish reviewed site version',exact:true});await expect(publishing).toBeVisible();
 const publish=publishing.getByRole('button',{name:'Publish selected reviewed version',exact:true});await expect(publish).toBeDisabled();
 await publishing.getByRole('button',{name:'Check live version',exact:true}).click();await expect(publishing).toContainText('No captured site version is currently live.');await expect(publish).toBeDisabled();
 await publishing.getByLabel('Confirm selected version replaces live site',{exact:true}).check();await publish.click();await expect(publishing).toContainText(`Live generation 1: ${state.hashActive}`);
 const response=await page.request.get(state.paths.directory);expect(response.status()).toBe(200);expect(response.headers()['x-site-version']).toBe(state.hashActive);expect(response.headers()['x-site-generation']).toBe('1');
});
test('existing admin publishes a reviewed update, recovers a lost reply and rolls back through the real host',async({page})=>{
 await page.goto('/frontbase-admin/login');await page.locator('input[type="email"]').fill(state.admin.email);await page.locator('input[type="password"]').fill(state.admin.password);
 await page.locator('button[type="submit"]').click();await page.waitForURL(/dashboard|pages/);
 await page.goto(`/frontbase-admin/builder/${state.templatePageIds.directory}`);
 await page.getByTitle('Page Settings',{exact:true}).click();await page.getByRole('tab',{name:'Directory',exact:true}).click();
 const preparation=page.getByRole('region',{name:'Site preparation',exact:true});await expect(preparation).toBeVisible();
 await preparation.getByLabel('Prepared version ID',{exact:true}).fill(state.hashNoContacts);await preparation.getByRole('button',{name:'Reopen private version',exact:true}).click();
 const publishing=page.getByRole('region',{name:'Publish reviewed site version',exact:true});await expect(publishing).toBeVisible();
 await expect(publishing.getByRole('button',{name:'Publish selected reviewed version',exact:true})).toBeDisabled();
 await publishing.getByRole('button',{name:'Check live version',exact:true}).click();await expect(publishing).toContainText(`Live generation 1: ${state.hashActive}`);
 await page.setViewportSize({width:390,height:844});await expect(publishing).toBeVisible();
 expect(await publishing.evaluate(element=>element.scrollWidth<=element.clientWidth)).toBe(true);
 const beforePages=await page.evaluate(async()=>{const response=await fetch('/api/pages/',{credentials:'include'});return {status:response.status,text:await response.text()};});expect(beforePages.status).toBe(200);
 let writes=0;
 await page.route('**/publication/activate/',async route=>{writes++;await route.fetch();await route.abort('failed');});
 await publishing.getByLabel('Confirm selected version replaces live site',{exact:true}).check();await publishing.getByRole('button',{name:'Publish selected reviewed version',exact:true}).click();
 await expect(publishing).toContainText('The selected version is currently live. This check does not identify which attempt published it.');expect(writes).toBe(1);
 await expect(publishing).toContainText(`Live generation 2: ${state.hashNoContacts}`);await expect(publishing.getByRole('button',{name:'Publish selected reviewed version',exact:true})).toBeDisabled();
 const updated=await page.request.get(state.paths.directory);expect(updated.status()).toBe(200);expect(updated.headers()['x-site-version']).toBe(state.hashNoContacts);expect(updated.headers()['x-site-generation']).toBe('2');
 expect(await updated.text()).not.toContain('mailto:');
 await page.unroute('**/publication/activate/');
 await preparation.getByLabel('Prepared version ID',{exact:true}).fill(state.hashActive);await preparation.getByRole('button',{name:'Reopen private version',exact:true}).click();
 await expect(publishing).toContainText(`Selected version: ${state.hashActive}`);await expect(publishing.getByRole('button',{name:'Publish selected reviewed version',exact:true})).toBeDisabled();
 await publishing.getByRole('button',{name:'Check live version',exact:true}).click();await expect(publishing).toContainText(`Live generation 2: ${state.hashNoContacts}`);
 await publishing.getByLabel('Confirm selected version replaces live site',{exact:true}).check();await publishing.getByRole('button',{name:'Publish selected reviewed version',exact:true}).click();
 await expect(publishing).toContainText(`Live generation 3: ${state.hashActive}`);
 const restored=await page.request.get(state.paths.directory);expect(restored.status()).toBe(200);expect(restored.headers()['x-site-version']).toBe(state.hashActive);expect(restored.headers()['x-site-generation']).toBe('3');expect(await restored.text()).toContain('mailto:');
 const afterPages=await page.evaluate(async()=>{const response=await fetch('/api/pages/',{credentials:'include'});return {status:response.status,text:await response.text()};});expect(afterPages.status).toBe(200);expect(afterPages.text).toBe(beforePages.text);
 const stale=await page.evaluate(async({hash,expected})=>(await fetch('/api/project/site-configuration/publication/activate/',{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify({hash,expected})})).status,{hash:state.hashNoContacts,expected:{schemaVersion:1,generation:1,hash:state.hashActive}});expect(stale).toBe(409);
 expect((await page.request.get(state.paths.directory)).headers()['x-site-generation']).toBe('3');
});
