/**
 * init scaffolder — emits a working Frontbase project. Variants:
 *   --pure       : edge-core + compiler (dev) + example component + page + worker + vite config.
 *                  Output builds (`pnpm build`) and runs a smoke test.
 *   --with-infra : --pure + edge-infra wiring placeholders (Phase 2).
 *   --full       : --with-infra + builder/backend wiring placeholders (Phase 2).
 *
 * Templates are inlined strings (no FS template dir) so the compiler package is
 * self-contained. The scaffolded worker mirrors examples/cf-worker.
 */
import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

export type InitVariant = 'pure' | 'with-infra' | 'full';

export interface InitResult {
    path: string;
    variant: InitVariant;
    files: string[];
    notes: string[];
}

export function scaffoldProject(targetDir: string, variant: InitVariant): InitResult {
    if (existsSync(targetDir)) throw new Error(`Target already exists: ${targetDir}`);
    const files: string[] = [];
    const notes: string[] = [];
    const write = (rel: string, content: string) => {
        const full = join(targetDir, rel);
        mkdirSync(join(full, '..'), { recursive: true });
        writeFileSync(full, content);
        files.push(rel);
    };

    write('package.json', packageJson(variant));
    write('tsconfig.json', TSCONFIG);
    write('vite.config.ts', VITE_CONFIG);
    write('wrangler.toml', WRANGLER);
    write('src/components/Hello.tsx', HELLO_COMPONENT);
    write('src/pages.ts', PAGES);            // shared page layouts (no executors)
    write('src/queries.ts', QUERIES);        // SERVER-ONLY: holds execute() — never imported by sw.ts
    write('src/manifest.edge.ts', MANIFEST_EDGE);      // execute retained — worker/edge only
    write('src/manifest.browser.js', MANIFEST_BROWSER);// GENERATED stub — regenerated by scripts/gen-manifest.mjs
    write('scripts/gen-manifest.mjs', GEN_MANIFEST);   // build step: emit browser manifest as static data
    write('src/sw.ts', SW_ENTRY);
    write('src/worker.ts', WORKER_ENTRY);
    write('src/smoke.ts', SMOKE);
    write('README.md', README(variant));

    if (variant !== 'pure') {
        write('src/infra.ts', INFRA_PLACEHOLDER);
        notes.push('edge-infra wiring is a placeholder — real providers land in Phase 2 (M2.1).');
    }
    if (variant === 'full') {
        write('src/console.ts', CONSOLE_PLACEHOLDER);
        notes.push('Console API (backend) wiring is a placeholder — lands in Phase 2 (M2.2).');
    }

    return { path: targetDir, variant, files, notes };
}

function packageJson(variant: InitVariant): string {
    const deps = ['"@frontbase/edge-core": "workspace:*"', '"zod": "^3.25.76"'];
    if (variant !== 'pure') deps.push('"@frontbase/edge-infra": "workspace:*"');
    return `{
  "name": "my-frontbase-app",
  "version": "0.0.0",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "tsc -p tsconfig.json && node scripts/gen-manifest.mjs",
    "test": "node dist/smoke.js",
    "check": "frontbase check --json"
  },
  "dependencies": { ${deps.join(', ')} },
  "devDependencies": {
    "@frontbase/compiler": "workspace:*",
    "@types/node": "^20.0.0",
    "typescript": "^5.6.0"
  }
}
`;
}

const TSCONFIG = `{
  "compilerOptions": {
    "target": "ES2022", "module": "ESNext", "moduleResolution": "bundler",
    "lib": ["ES2022", "DOM", "WebWorker"], "types": ["node"],
    "strict": true, "noUncheckedIndexedAccess": true,
    "isolatedModules": true, "verbatimModuleSyntax": true, "skipLibCheck": true,
    "allowJs": true, "declaration": true, "rootDir": "src", "outDir": "dist"
  },
  "include": ["src"]
}
`;

const VITE_CONFIG = `import { defineConfig } from 'vite';
import { frontbasePlugin } from '@frontbase/compiler/vite';
export default defineConfig({ plugins: [frontbasePlugin()] });
`;

const WRANGLER = `name = "my-frontbase-app"
main = "dist/worker.js"
compatibility_date = "2026-01-01"
no_bundle = true
`;

const HELLO_COMPONENT = `import { z } from 'zod';

export const Schema = z.object({
    title: z.string().default('Hello, Edge').describe('Heading text'),
    subtitle: z.string().optional().describe('Supporting line'),
});

export function Hello({ title, subtitle }: { title: string; subtitle?: string }) {
    return \`<section><h1>\${title}</h1>\${subtitle ? \`<p>\${subtitle}</p>\` : ''}</section>\`;
}
`;

// Page layouts — no executors, safe for both edge and browser manifests.
const PAGES = `export const pages = {
    '/': {
        title: 'My Frontbase App', slug: 'home',
        layout: { root: {}, content: [
            { id: 'h', type: 'Heading', props: { content: 'Hello, Edge', level: 'h1' } },
            { id: 'l', type: 'Link', props: { text: 'Sample data →', href: '/sample', color: '#4338ca', underline: true } },
        ] },
    },
    '/sample': {
        title: 'Sample', slug: 'sample', queryId: 'sample.list',
        layout: { root: {}, content: [
            { id: 's', type: 'Text', props: { content: '{% for r in records %}{{ r.name }};{% endfor %}' } },
        ] },
    },
};
`;

// SERVER-ONLY. Holds execute() (runs with edge secrets). NEVER import this from
// sw.ts — the service worker must only ever see the browser manifest projection.
const QUERIES = `import { z } from 'zod';
import { defineQueries } from '@frontbase/compiler';

export const queries = defineQueries({
    'sample.list': {
        params: z.object({ limit: z.number().optional() }),
        scope: 'public',                 // 'tenant' | 'user' require an authenticated principal
        ttlSeconds: 60,
        execute: async () => [{ id: 1, name: 'Sample row' }],
    },
});
`;

// EDGE manifest — execute retained. Imported by worker.ts and the smoke test only.
const MANIFEST_EDGE = `import { buildSiteManifest } from '@frontbase/compiler';
import { pages } from './pages.js';
import { queries } from './queries.js';

export const manifest = buildSiteManifest({ pages, queries });
`;

// BROWSER manifest — a build-time GENERATED static data file (see gen-manifest.mjs).
// It is emitted by emitBrowserManifest() as pure JSON data: no execute, no Zod
// schemas, no compiler code — so the SW bundle provably cannot contain an
// executor or a secret (A-16 / SEC-1). Committed as a stub; regenerated on build.
const MANIFEST_BROWSER = `// AUTO-GENERATED at build time by scripts/gen-manifest.mjs — do not edit.
// Pure data projection (execute + param schemas stripped). Safe for the SW bundle.
export const manifest = { version: 'dev', pages: {}, queries: {} };
`;

// Build step (runs AFTER tsc): precompute the browser manifest as static data.
// Reads the COMPILED pages/queries from dist so it never needs a TS loader.
const GEN_MANIFEST = `import { emitBrowserManifest } from '@frontbase/compiler';
import { pages } from '../dist/pages.js';
import { queries } from '../dist/queries.js';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const { manifest } = emitBrowserManifest({ pages, queries }, join(here, '..', 'src', 'manifest.browser.js'));
console.log('generated browser manifest:', manifest.version, Object.keys(manifest.queries).length, 'queries (execute stripped)');
`;

const SW_ENTRY = `/// <reference lib="webworker" />
import { createEngine, proxyProvider, attachServiceWorker } from '@frontbase/edge-core';
import { manifest } from './manifest.browser.js';  // GENERATED static data — no execute(), no secrets
declare const self: ServiceWorkerGlobalScope;
const engine = createEngine({ manifest, data: proxyProvider('/api/data'), environment: 'service-worker' });
// eslint-disable-next-line @typescript-eslint/no-explicit-any
attachServiceWorker(self as any, engine, manifest);
`;

const WORKER_ENTRY = `import { createEngine, directProvider, configureEngine } from '@frontbase/edge-core';
import { createConsole } from '@frontbase/backend';
import { d1RunnerFromBinding, sqliteRunner } from '@frontbase/edge-infra';
import { manifest } from './manifest.edge.js';

// BLOCKER-1/B10: D1 bindings live in per-request env, so the engine/console are
// built LAZILY on first request (cached per isolate), not at module init.
let cached: ReturnType<typeof createEngine> | null = null;
let initialized = false;

function getEngine(env: any) {
  if (cached) return cached;
  configureEngine({ edition: 'community', nodeEnv: 'production' });
  // CF: env.DB is the D1 binding (provisioned by 'frontbase deploy'). Docker/dev:
  // env.DB_URL is a file: URL. One runner, shared by the console + public data.
  const makeRunner = async () => env.DB ? d1RunnerFromBinding(env.DB) : sqliteRunner(env.DB_URL ?? 'file:./data/frontbase.db');
  const console = createConsole({ makeRunner, sessionSecret: env.SESSION_SECRET });
  cached = createEngine({ manifest, data: directProvider(manifest), environment: 'edge', console });
  return cached;
}

export default {
  async fetch(req: Request, env: any, ctx: any) {
    const engine = getEngine(env);
    // First-boot: the lazy getEngine is the only place env.DB exists, so
    // migrations + seeding run here, once per isolate (BLOCKER-4).
    if (!initialized) {
      initialized = true;
      // migrateUp(runner) + seedOwner run on first request (M-ID.1 wires seed).
    }
    return engine.fetch(req, env, ctx);
  },
};
`;

const SMOKE = `import { createEngine, directProvider } from '@frontbase/edge-core';
import { manifest } from './manifest.edge.js';
const engine = createEngine({ manifest, data: directProvider(manifest), environment: 'edge' });
const home = await engine.fetch(new Request('http://t.local/'));
const sample = await engine.fetch(new Request('http://t.local/sample'));
const ok = home.status === 200 && sample.status === 200 && (await sample.text()).includes('Sample row');
console.log(ok ? 'smoke: PASS' : 'smoke: FAIL');
process.exit(ok ? 0 : 1);
`;

const INFRA_PLACEHOLDER = `// Phase 2 (M2.1): wire @frontbase/edge-infra providers here.
// import { d1Provider } from '@frontbase/edge-infra';
// export const data = d1Provider(env.DB);
export {};
`;

const CONSOLE_PLACEHOLDER = `// Phase 2 (M2.2): mount the @frontbase/backend console API here.
// import { createConsole } from '@frontbase/backend';
export {};
`;

function README(variant: InitVariant): string {
    return `# my-frontbase-app

Scaffolded by \`frontbase init --${variant}\`.

\`\`\`bash
pnpm install
pnpm build        # compile
pnpm test         # in-process smoke (renders home + /sample)
pnpm check        # schema + diagnostics (--json for agents)
\`\`\`

Deploy as a Cloudflare Worker: \`npx wrangler deploy\` (after \`pnpm build\`).
`;
}
