/**
 * Regenerate src/ssr/iconMap.ts — the bundled lucide icon name→SVG map.
 *
 * WHY: the framework eSSR has no React at runtime. The product builder picks
 * icons by lucide-react PascalCase name (e.g. "Zap", "CheckCircle2"). To render
 * them as REAL svg server-side (true WYSIWYG with the builder canvas) we render
 * every lucide-react export to static SVG here — using the EXACT lucide-react
 * version the builder ships (0.462.0) — and store the inner path markup keyed by
 * PascalCase name. This also resolves lucide's deprecated aliases (CheckCircle2,
 * XCircle, …) which exist only in lucide-react's exports, not in lucide-static.
 *
 * This is a CODEGEN step: react / react-dom / lucide-react are devDeps and are
 * NOT shipped to the edge. Same pattern as regen-utilities.mjs → utilitiesCss.ts.
 *
 * Run: node scripts/regen-icons.mjs   (after `pnpm install` in edge-core)
 */
import { renderToStaticMarkup } from 'react-dom/server';
import React from 'react';
import * as Lucide from 'lucide-react';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, '..', 'src', 'ssr', 'iconMap.ts');

// The parity allowlist: exactly the icon names the product builder exposes in its
// IconPicker ICON_MAP (one PascalCase name per line). Rendering only these keeps
// the bundled map lean (~770 icons, not lucide's full 3500). Regenerate this file
// from the product when its icon set changes:
//   sed -n '/ICON_MAP:/,/^[}]/p' <product>/.../IconPicker.tsx | grep -oE "[A-Z][A-Za-z0-9]+" | sort -u
const allow = new Set(
    readFileSync(join(here, 'builder-icons.txt'), 'utf8')
        .split('\n').map((s) => s.trim()).filter(Boolean)
);

const map = {};
let nonSvg = 0;
let notInLucide = [];
for (const name of allow) {
    const Comp = Lucide[name];
    if (Comp == null || (typeof Comp !== 'object' && typeof Comp !== 'function')) { notInLucide.push(name); continue; }
    try {
        const svg = renderToStaticMarkup(React.createElement(Comp, { size: 24, strokeWidth: 2 }));
        if (!svg.startsWith('<svg')) { nonSvg++; continue; }
        // Keep only the inner markup (paths/circles/lines/rects). The wrapping
        // <svg> attributes are re-applied by renderIcon to control size/color.
        const inner = svg.replace(/^<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '');
        if (!inner.trim()) { nonSvg++; continue; }
        map[name] = inner;
    } catch {
        nonSvg++;
    }
}
if (notInLucide.length) {
    console.warn(`regen-icons: ${notInLucide.length} allowlist names not in lucide-react: ${notInLucide.join(', ')}`);
}

const entries = Object.keys(map)
    .sort()
    .map((k) => `    ${JSON.stringify(k)}: ${JSON.stringify(map[k])}`);

const version = (Lucide.default ?? {}).version ?? '0.462.0';
const out = `/* GENERATED by scripts/regen-icons.mjs — DO NOT EDIT BY HAND.
 * Bundled lucide icon name (PascalCase) → inner SVG markup (paths/circles/…).
 * Rendered from lucide-react@${version} — the exact version the product builder
 * ships — so published eSSR icons are equivalent to the builder canvas, including
 * lucide's deprecated aliases (CheckCircle2, XCircle, …).
 *
 * react / react-dom / lucide-react are CODEGEN-ONLY devDeps; they are NOT shipped
 * to the edge. Regenerate after bumping lucide-react: node scripts/regen-icons.mjs
 */
export const LUCIDE_ICONS: Record<string, string> = {
${entries.join(',\n')}
};

export const LUCIDE_ICON_COUNT = ${entries.length};
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, out, 'utf8');
console.log(`regen-icons: wrote ${entries.length} icons → src/ssr/iconMap.ts (${nonSvg} non-icon exports skipped)`);
