/**
 * Runtime configuration for the GENERATED API client (CF-22 P0 / W2).
 *
 * `src/client/` is fully generated by @hey-api/openapi-ts from
 * fastapi-backend/contracts/openapi.full.json — never edit it by hand
 * (`npm run client:generate` to regenerate). This module wires the generated
 * axios client to the exact runtime behavior of the legacy instance in
 * services/api-service.ts so migrated services behave identically:
 *
 *   - relative base URL (dev: Vite proxy · prod: Nginx reverse proxy)
 *   - cookie credentials (self-host session auth)
 *   - cloud mode: Bearer token (Supabase or SuperTokens) + X-Project-Id header
 *
 * Imported once for side effects at app bootstrap (main.tsx), before any
 * generated SDK call.
 */
import { client } from '@/client/client.gen';
import { isCloud } from '@/lib/edition';
import { getAuthClient, isSupabaseAuth } from '@/lib/auth/AuthClientFactory';
import { useAuthStore } from '@/stores/auth';

client.setConfig({
    baseURL: '', // relative — Vite proxy in dev, Nginx in production
    timeout: 10_000,
    withCredentials: true,
});

client.instance.interceptors.request.use(async (config) => {
    if (isCloud()) {
        let token: string | null = null;

        if (isSupabaseAuth()) {
            try {
                token = await getAuthClient().getToken();
            } catch (error) {
                console.warn('[api-client] Failed to get token from AuthClient:', error);
            }
        } else {
            token = useAuthStore.getState().token;
        }

        if (token) {
            config.headers['Authorization'] = `Bearer ${token}`;
        }

        // Multi-project: read from localStorage to avoid a circular import with
        // the project store; the store keeps this value in sync.
        const activeProjectId = localStorage.getItem('activeProjectId');
        if (activeProjectId) {
            config.headers['X-Project-Id'] = activeProjectId;
        }
    }
    return config;
});

export { client };
