/**
 * @frontbase/backend — the in-worker console API. A Hono sub-router the host
 * mounts via createEngine({ console }) at /api/console. SERVER-ONLY.
 *
 *   createConsole({ makeRunner, resolvePrincipal?, sessionSecret?, queries?, ... }) → Hono
 *
 * `makeRunner` (Decision A-19/B1) returns a `DbRunner` — so the console speaks
 * SQLite / D1 / Turso / Postgres through one seam. `dbUrl` stays as a convenience
 * (builds a sqliteRunner) so Docker/tests are unchanged. Default-DENY auth
 * (RULE 2); Drizzle is the single source of truth (A-13); opaque errors (RULE 4).
 *
 * `sessionSecret` (BLOCKER-2) is the identity seam: when `resolvePrincipal` is
 * omitted but `sessionSecret` is given, one is built for the `fb_session` JWT
 * cookie (wired in M-ID.1).
 */
import { Hono } from 'hono';
import type { Principal } from '@frontbase/edge-core';
import type { DbRunner } from '@frontbase/edge-infra';
import { sqliteRunner, createResolvePrincipal, s3StorageProvider, cloudflareProvisioner, supabaseProvisioner, noopProvisioner, type StorageProvider, type Provisioner } from '@frontbase/edge-infra';
import type { QueryRegistry } from '@frontbase/compiler/manifest';
import { defaultDenyAuth, type ConsoleAuthVars } from './mw/auth.js';
import { opaqueErrors } from './mw/errors.js';
import { pagesRoutes } from './routes/pages.js';
import { healthRoutes } from './routes/health.js';
import { publishRoutes } from './routes/publish.js';
import { ConsoleStore } from './db/store.js';
import { UserStore } from './db/users.js';
import { authRoutes, meRoute } from './auth/routes.js';
import { tenantsRoutes } from './routes/tenants.js';
import { setupRoutes } from './routes/setup.js';
import { phase2Routes } from './routes/phase2.js';
import { recoverStuckExecutions } from './routes/phase2.js';
import { usersRoutes } from './routes/users.js';
import { dataStudioRoutes } from './routes/data-studio.js';
import { plansRoutes } from './routes/plans.js';
import { Phase2Store } from './db/phase2-store.js';
import { createSecretCipher, noopCipher, type SecretCipher } from './db/secret-cipher.js';
import { requireRole, canActOnTenant } from './auth/roles.js';

export interface CreateConsoleDeps {
    /** Build the DbRunner for the console DB (env-aware; e.g. from env.DB on CF).
     *  Called lazily per tenant. */
    makeRunner: () => Promise<DbRunner> | DbRunner;
    /** Resolve the calling principal. If omitted but sessionSecret is given, one is
     *  built for the fb_session JWT cookie (M-ID.1). Default: anonymous. */
    resolvePrincipal?: (req: Request) => Promise<Principal>;
    /** HS256 secret for the session JWT (identity seam — M-ID.1). */
    sessionSecret?: string;
    /** libsql URL convenience (Docker/tests) — builds sqliteRunner when makeRunner
     *  is not provided. */
    dbUrl?: string;
    /** Registered queries (for the publish pipeline's manifest). */
    queries?: QueryRegistry;
    /** Cache purge callback (publish invalidation). Default: no-op. */
    purgeCache?: (keys: string[]) => Promise<void>;
    /** Clock (deterministic in tests). Default: () => new Date().toISOString(). */
    now?: () => string;
    /** Setup wizard token (SETUP_TOKEN env secret). If unset, browser setup is
     *  disabled so a public first visitor cannot claim the deployment. */
    setupToken?: string;
    /** Expiry for the setup capability generated by deploy. */
    setupExpiresAt?: string;
    /** Role the first admin is seeded as via /setup (ADMIN_ROLE at deploy).
     *  Fixed server-side — the request body can NOT choose it (SEC CRIT-2). Default 'owner'. */
    seedRole?: string;
    /** Object-storage config (F4). When provided, file upload/download round-trips
     *  real bytes via the S3-compatible provider (R2/S3/B2/MinIO). */
    storage?: { accessKeyId: string; secretAccessKey: string; endpoint?: string; region?: string };
    /** A pre-built StorageProvider (tests / advanced hosts). Takes precedence over
     *  `storage` credentials — lets a test inject a memory provider end-to-end. */
    storageProvider?: StorageProvider;
    /** Cloudflare provisioning config (F5). When provided, edge-resource create
     *  provisions a REAL D1/KV/Queue via the Management API. */
    provisioning?: { accountId: string; apiToken: string };
    /** Supabase host-project config (F5c Option A). When provided, edge-resource
     *  create provisions a Postgres schema (database) / pgvector schema (vector).
     *  Mutually exclusive with `provisioning` for v1 — CF wins if both are set. */
    supabaseProvisioning?: { url: string; serviceKey: string; schemaPrefix?: string };
    /** A pre-built Provisioner (tests / advanced hosts). Takes precedence over
     *  `provisioning` creds — lets a test inject a mock end-to-end. */
    provisioner?: Provisioner;
    /** Background work dispatcher (F3b). When provided, workflow execution is
     *  async (fire-and-track). On CF, wire to ctx.waitUntil; in-process tests can
     *  use queueMicrotask. Default: synchronous. */
    dispatcher?: (work: () => Promise<void>) => void;
}

export async function createConsole(deps: CreateConsoleDeps): Promise<Hono<{ Variables: ConsoleAuthVars }>> {
    const now = deps.now ?? (() => new Date().toISOString());
    const purge = deps.purgeCache ?? (async () => {});

    // Resolve the runner factory: explicit makeRunner wins; dbUrl builds sqliteRunner.
    // createConsole is built once per isolate inside getEngine(env), so resolving the
    // runner here is fine — it's the env-bound D1 binding (or a file/:memory: URL).
    const makeRunner = deps.makeRunner ?? (async () => sqliteRunner(deps.dbUrl ?? ':memory:'));
    let sharedRunner = await makeRunner();

    // Resolve the principal resolver: explicit wins; sessionSecret builds one for
    // the fb_session JWT cookie (M-ID.1, D2); else anonymous.
    const resolvePrincipal = deps.resolvePrincipal
        ?? (deps.sessionSecret ? createResolvePrincipal({ jwtSecret: deps.sessionSecret, jwtCookie: 'fb_session' })
            : (async () => ({ user: null, tenant: undefined })));

    // Stores per tenant — built synchronously from the shared runner. RULE 6: one runner.
    const stores = new Map<string, ConsoleStore>();
    const storeFor = (tenant: string): Promise<ConsoleStore> => {
        let s = stores.get(tenant);
        if (!s) { s = new ConsoleStore(sharedRunner, tenant); stores.set(tenant, s); }
        return Promise.resolve(s);
    };
    const userStores = new Map<string, UserStore>();
    const userStoreFor = (tenant: string): UserStore => {
        let s = userStores.get(tenant);
        if (!s) { s = new UserStore(sharedRunner, tenant); userStores.set(tenant, s); }
        return s;
    };
    // Phase 2 stores per tenant (automations, edge resources, storage, settings, variables).
    // Secret variables are encrypted at rest (F6) — the cipher is built once from the
    // session secret (or a dedicated SECRETS_KEY if provided).
    const secretCipher: SecretCipher = deps.sessionSecret
        ? await createSecretCipher(deps.sessionSecret).catch(() => noopCipher)
        : noopCipher;
    const phase2Stores = new Map<string, Phase2Store>();
    const phase2StoreFor = (tenant: string): Phase2Store => {
        let s = phase2Stores.get(tenant);
        if (!s) { s = new Phase2Store(sharedRunner, tenant, secretCipher); phase2Stores.set(tenant, s); }
        return s;
    };

    const app = new Hono<{ Variables: ConsoleAuthVars }>();
    app.onError(opaqueErrors);

    // /health + login/logout + setup are UNAUTHENTICATED (pre-init / you can't require a session to log in).
    app.route('/health', healthRoutes());
    // Setup wizard (M-ID.3 + DB picker) — outside default-deny (no session exists pre-init).
    // seedRole comes from deploy config (ADMIN_ROLE), NOT the request body (SEC CRIT-2).
    app.route('/', setupRoutes({
        userStoreFor,
        setupToken: deps.setupToken,
        setupExpiresAt: deps.setupExpiresAt,
        seedRole: deps.seedRole,
        setRunner: (r) => { sharedRunner = r; },
        claimInitialization: async (at) =>
            (await sharedRunner.exec('UPDATE setup_state SET initialized_at = ? WHERE id = 1 AND initialized_at IS NULL', [at])) === 1,
        releaseInitialization: async () => {
            await sharedRunner.exec('UPDATE setup_state SET initialized_at = NULL WHERE id = 1');
        },
        now,
    }));
    if (deps.sessionSecret) {
        app.route('/', authRoutes({ userStoreFor, sessionSecret: deps.sessionSecret }));
    }
    // Everything below requires an authenticated principal (default-deny).
    app.use('*', defaultDenyAuth(resolvePrincipal));
    app.route('/', pagesRoutes(storeFor, now));
    app.route('/', publishRoutes(storeFor, deps.queries ?? {}, purge, now, phase2StoreFor));
    if (deps.sessionSecret) {
        app.route('/', meRoute()); // /me — principal already resolved
        app.route('/', tenantsRoutes(() => sharedRunner, userStoreFor, now)); // /tenants — master_admin only (M-ID.2)
    }
    // CF-18 Phase 2: automations, edge resources, storage, settings, variables, users.
    // F4: a real object-storage provider when credentials are configured (or a
    // pre-built one injected for tests — the injection seam takes precedence).
    // F5: a real CF provisioner when accountId + apiToken are configured.
    const storageProvider: StorageProvider | undefined =
        deps.storageProvider ?? (deps.storage ? s3StorageProvider(deps.storage) : undefined);
    // F5/F5c provisioner. Precedence: injected > CF > Supabase > noop. CF wins if
    // both CF and Supabase creds are configured (platform-native path); warn once.
    let provisioner: Provisioner;
    if (deps.provisioner) {
        provisioner = deps.provisioner;
    } else if (deps.provisioning) {
        if (deps.supabaseProvisioning) console.warn('[frontbase] both CF and Supabase provisioning configured — CF wins; Supabase ignored');
        provisioner = cloudflareProvisioner(deps.provisioning);
    } else if (deps.supabaseProvisioning) {
        provisioner = supabaseProvisioner(deps.supabaseProvisioning);
    } else {
        provisioner = noopProvisioner;
    }
    app.route('/', phase2Routes(phase2StoreFor, now, storageProvider, provisioner, deps.dispatcher));
    app.route('/', usersRoutes(userStoreFor, now, phase2StoreFor));
    // Phase 3b: Data Studio (datasources + introspection) + Plans
    app.route('/', dataStudioRoutes(phase2StoreFor, now));
    app.route('/', plansRoutes(phase2StoreFor, now));

    // F3b-durable: one-shot recovery on boot. If async dispatch is configured, a
    // previous isolate may have died mid-run, leaving 'running' rows behind. Replay
    // them (best-effort, opaque on error) using the dispatcher so on CF it rides
    // ctx.waitUntil of the first request. Default cutoff: runs older than 5 min.
    if (deps.dispatcher) {
        const cutoffIso = new Date(Date.now() - 5 * 60_000).toISOString();
        deps.dispatcher(async () => {
            try { await recoverStuckExecutions(phase2StoreFor, now, cutoffIso); }
            catch { /* best-effort: a failed sweep retries on the next boot */ }
        });
    }

    return app;
}

export { ConsoleStore, defaultDenyAuth, opaqueErrors };
export { UserStore, toPublic } from './db/users.js';
export type { UserRecord, PublicUser } from './db/users.js';
export { seedOwner } from './auth/seed.js';
export { authRoutes, meRoute } from './auth/routes.js';
export { requireRole, canActOnTenant } from './auth/roles.js';
export { TenantStore } from './db/tenants.js';
export type { TenantRecord } from './db/tenants.js';
export { Phase2Store } from './db/phase2-store.js';
export { createSecretCipher, noopCipher } from './db/secret-cipher.js';
export type { SecretCipher } from './db/secret-cipher.js';
export { tenantsRoutes } from './routes/tenants.js';
export { publishPage } from './publish/pipeline.js';
export { migrateUp, migrateDown, appliedVersions, schemaFingerprint, MIGRATIONS } from './db/migrations.js';
export type { Migration } from './db/migrations.js';
// CF-22 P1: product-compatible /api surface + drift-gate machinery.
export { createCompatApp } from './compat/app.js';
export type { CreateCompatAppDeps } from './compat/app.js';
export { buildFrameworkSpec, productOps, productSpec, opKey, routedOps, implementedOps } from './compat/app.js';
export * from './db/schema.js';
