/**
 * Type generator — manifest → a TypeScript .d.ts string equal to z.infer<typeof Schema>.
 */
import type { ComponentManifest, PropertyField } from './types.js';

export function tsType(f: PropertyField): string {
    let base: string;
    switch (f.kind) {
        case 'string': base = 'string'; break;
        case 'number': base = 'number'; break;
        case 'boolean': base = 'boolean'; break;
        case 'enum': base = f.enum ? f.enum.map((v) => JSON.stringify(v)).join(' | ') : 'string'; break;
        case 'array': base = `Array<${f.element ? tsType(f.element) : 'unknown'}>`; break;
        case 'object': base = `{ ${f.properties?.map((p) => tsField(p)).join('; ') ?? ''} }`; break;
        default: base = 'unknown';
    }
    return f.nullable ? `${base} | null` : base;
}

export function tsField(f: PropertyField): string {
    const optional = !f.required ? '?' : '';
    return `${f.name}${optional}: ${tsType(f)}`;
}

export function generateTypes(manifest: ComponentManifest): string {
    const fields = manifest.properties.map(tsField).join('; ');
    return `// AUTO-GENERATED by @frontbase/compiler — do not edit
export type ${manifest.name}Props = { ${fields} };
`;
}
